### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by molnarg** [cure53/HTTPLeaks#11]
Please add a license. It would be nice to have a permissive one so that this can easily be included in tests in other projects.

**Comment by cure53** [comment]
Which one would you prefer? Same as the ones for e.g. DOMPurify?

**Comment by daknob** [comment]
@cure53 BSD 2-Clause or 3-Clause is nice. Otherwise MIT will suffice.

**Comment by cure53** [comment]
I have no objections, mind sending us a PR?

**Comment by daknob** [comment]
@cure53 Coming up in a minute. Thanks! :-)

**Comment by molnarg** [comment]
Perfect, thanks!
