### ISSUE TITLE
Web fonts

### ISSUE THREAD

**Issue by xem** [cure53/HTTPLeaks#14]
Hi, great work!
You could consider using the cross-browser syntax(es) for css @font-face, as it (they) uses many URLs:
http://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/
Cheers

**Comment by cure53** [comment]
Thanks :) Good point too - but what exactly would you improve?

Mind sending us a PR?

**Comment by xem** [comment]
Just sent a PR your way.
Feel free to edit it (or ignore it if it's not relevant).
Cheers

**Comment by cure53** [comment]
Looking good, thx :)
