### ISSUE TITLE
typo ?

### ISSUE THREAD

**Issue by tst2005** [cure53/HTTPLeaks#24]
Hello,

I read the leak.html and see 
* https://github.com/cure53/HTTPLeaks/blob/master/leak.html#L277-L278
* https://github.com/cure53/HTTPLeaks/blob/master/leak.html#L359-L360
the URL contains `background-image-alias` but the trigger contains `border-image`.

Is it wanted or a typo ?

Regards,

**Comment by cure53** [comment]
That looks like a typo indeed, thanks for noticing. Fixed!
