### ISSUE TITLE
You have been added to awesome-humane-tech

### ISSUE THREAD

**Issue by aschrijver** [cure53/HTTPLeaks#33]
This is just a FYI issue to notify that you were added to the curated awesome-humane-tech in the 'Awareness' category, and - if you like that - are now entitled to wear our badge:

[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)

By adding this to the README:

```markdown
[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)
```

https://github.com/humanetech-community/awesome-humane-tech

**Comment by tst2005** [comment]
(we need a ironical badge :p )

**Comment by aschrijver** [comment]
Maybe not, if you confuse Humane Tech Community with Center for Humane Technology and that's your reason for feeling the emotion. We are wholly independent grassroots group (our website, not too well maintained is at https://humanetech.community but our forum is under humanetech.com subdomain).
