### ISSUE TITLE
js leaks missing

### ISSUE THREAD

**Issue by weizman** [cure53/HTTPLeaks#34]
not necessarily an issue, maybe more of a question:
why aren't there any JS examples?
mapping those might be important too, in order to have an inclusive documentation of all http leaks.
meaning, the following can count as an http leak after all:
```html
<script>
  fetch('https://leaked.com');
</script>
``` 
any thoughts? @cure53

**Comment by cure53** [comment]
Heya, sorry for a late reply :D Technically, that would be useful - but I wonder how many there are. Do you know of any comprehensive list?
