### ISSUE TITLE
XHTML external entitities

### ISSUE THREAD

**Issue by ConradIrwin** [cure53/HTTPLeaks#9]
I think this requires that the document is served up with content-type: application/xml (at least it seems to in chrome), so not sure if it's in scope. Note that you have to use the entity for the request to be made.

```
<!DOCTYPE html
[
  <!ENTITY foo SYSTEM "http://localhost:4000/sindex.xml">
]>
<html xmlns="http://www.w3.org/1999/xhtml">&foo;</html>
```

**Comment by cure53** [comment]
Hmm, in application/xml there is many more ways to leak data via HTTP. We should consider adding a separate page for that maybe?
